###############
## 
####

GPU: [0, 1, 2, 3]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'PMUNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 400
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  
  USE_GRAD_CLIP: False
  GRAD_CLIP_NORM: 5    
  LOG_GRADIENT_STATS: True    
  GRADIENT_LOG_INTERVAL: 5
  # NEPOCH_DECAY: [10]
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 2
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: './Datasets/train'       # path to training data
  VAL_DIR: './Datasets/test/Rain100L' # path to validation data
  SAVE_DIR: './checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
